apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payment-mongodb-pvc
  labels:
    app: payment-mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard  # Use 'standard' for Minikube
